version: '3.8'

services:
  stable-diffusion:
    build: .
    container_name: stable-diffusion-forge
    restart: unless-stopped
    ports:
      - "7860:7860"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PYTHONUNBUFFERED=1
    volumes:
      - ./models:/app/models
      - ./outputs:/app/outputs
      - ./extensions:/app/extensions
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: '4gb'